# -*- coding: utf-8 -*-
"""L&T Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FtKt9NofXjoMS4w-AJzx-L5reEHy9UOJ
"""

import pandas as pd
import pickle

pkl_path = "/content/LSWMD.pkl"   # change if needed

try:
    df = pd.read_pickle(pkl_path)
except Exception:
    with open(pkl_path, "rb") as f:
        df = pickle.load(f)

df.head(10)

list(df.columns)

import matplotlib.pyplot as plt
import numpy as np

# change this if your wafer map column has a different name
wafer_col = "waferMap"

sample_maps = df[wafer_col].head(5)

fig, axes = plt.subplots(1, 5, figsize=(20, 4))
for i, ax in enumerate(axes):
    wm = sample_maps.iloc[i]
    ax.imshow(wm, cmap="gray", interpolation="nearest")
    ax.set_title(f"Wafer {i+1}")
    ax.axis("off")

plt.tight_layout()
plt.show()

# number of unique lots
num_lots = df["lotName"].nunique()

# total training and test data counts
train_count = (df["trianTestLabel"] == "Training").sum()
test_count = (df["trianTestLabel"] == "Test").sum()

print("Number of lots:", num_lots)
print("Total training data:", train_count)
print("Total test data:", test_count)
print("Total rows: ", len(df))

list(df["failureType"].astype(str).dropna().unique())